TShirtShop/Controllers/ShirtController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TShirtShop.BLL;
using TShirtShop.Core;

using TShirtShop.Core.Models;
using TShirtShop.Core.ViewModels;
using TShirtShop.Data;
using TShirtShop.Helper;

namespace TShirtShop.Controllers
{
    public class ShirtController : Controller
    {
        private readonly ISizeRepository _sizeRepository;

        private readonly IShirtServices _shirtServices;
        private readonly IHtmlHelper _htmlHelper;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IMapper _mapper;


        public ShirtController(IShirtServices shirtServices, ISizeRepository sizeRepository, IHtmlHelper htmlHelper, IHostingEnvironment hostingEnvironment, IMapper mapper)
        {
            _shirtServices = shirtServices;
            _sizeRepository = sizeRepository;
            _htmlHelper = htmlHelper;
            _hostingEnvironment = hostingEnvironment;
            _mapper = mapper;
        }
        public async Task<IActionResult> ShirtSetting()
        {
            var shirts = await _shirtServices.GetShirts();
            return View(shirts);
        }
        public async Task<IActionResult> Index()
        {
            var shirts = await _shirtServices.GetShirts();
            return View(shirts);
        }
        [Authorize]
        public async Task<ActionResult> Add()
        {
            var shirtmodel = new ShirtViewModel();
            shirtmodel.Genders = _htmlHelper.GetEnumSelectList<GenderEnum>();
            var sizeResult = await _sizeRepository.GetAllSizes();
            shirtmodel.Sizes = sizeResult.Select(x => new SelectListItem { Value = x.SizeId.ToString(), Text = x.Name }).ToList();

            return View(shirtmodel);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Save(ShirtViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("Add", viewModel);
            string webRootPath = _hostingEnvironment.WebRootPath;

            var files = HttpContext.Request.Form.Files;
            var inputStream = HttpContext.Request.Body;

            var shirt = _mapper.Map<Shirt>(viewModel);
            //if (viewModel.Id != 0)
            //{
            //    shirt = await _shirtServices.GetShirtBy(viewModel.Id);
            //}


            if (files.Count > 0)
            {
                var uploads = Path.Combine(webRootPath, "images");
                var extension = Path.GetExtension(files[0].FileName);
                var imageHelper = new ImageHelper();

                //Delete the existing images

                if (shirt.ShirtId > 0)
                {
                    var imagePathOriginal = Path.Combine(webRootPath, shirt.ImageLocation.TrimStart('\\'));
                    var imagePathThumb = Path.Combine(webRootPath, shirt.ImageThumnNailLocation.TrimStart('\\'));

                    if (System.IO.File.Exists(imagePathOriginal))
                    {
                        System.IO.File.Delete(imagePathOriginal);
                       
                    }
                    if (System.IO.File.Exists(imagePathThumb))
                    {
                        System.IO.File.Delete(imagePathThumb);
                    }

                }

                //Upload new images
                shirt.ImageLocation = imageHelper.GetImagePath(files, uploads);
                shirt.ImageThumnNailLocation = imageHelper.GetThumnailPath(shirt.ImageLocation, uploads, extension);
            }
            else
            {
                var shirtdb = await _shirtServices.GetShirtBy(shirt.ShirtId);
                shirt.ImageLocation = shirtdb.ImageLocation;
                shirt.ImageThumnNailLocation = shirtdb.ImageThumnNailLocation;


            }

            if (shirt.ShirtId > 0)
            {
                _shirtServices.Update(shirt);
            }
            else
                _shirtServices.Insert(shirt);



            return RedirectToAction("Index");
        }
        [Authorize]
        public async Task<ActionResult> Edit(int id)
        {
            var shirt = await _shirtServices.GetShirtBy(id);
            var shiftViewModel = new ShirtViewModel();
            shiftViewModel = _mapper.Map<ShirtViewModel>(shirt);
            shiftViewModel.Genders = _htmlHelper.GetEnumSelectList<GenderEnum>();
            var sizeResult = await _sizeRepository.GetAllSizes();
            shiftViewModel.Sizes = sizeResult.Select(x => new SelectListItem { Value = x.SizeId.ToString(), Text = x.Name }).ToList();

            return View(shiftViewModel);
        }
        public async Task<ActionResult> Delete (int id)
        {
            var shirt = await _shirtServices.GetShirtBy(id);
            if(shirt != null)
            {
                shirt.IsActive = false;
                _shirtServices.Update(shirt);
            }
            return RedirectToAction("Index");
        }
    }
}

TShirtShop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TShirtShop.BLL;
using TShirtShop.Core.ViewModels;
using TShirtShop.Data;

namespace TShirtShop.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IShirtRepository _shirtRepository;
        private readonly ShoppingCartServices _shoppingCartServices;

        public ShoppingCartController(IShirtRepository shirtRepository,ShoppingCartServices shoppingCartServices)
        {   
            _shirtRepository = shirtRepository;
            _shoppingCartServices = shoppingCartServices;
        }
        public IActionResult Index()
        {
            var items = _shoppingCartServices.GetShoppingCartItems();
            _shoppingCartServices.ShoppingCartItems = items;
            var shoppingCartViewModel = new ShoppingCartViewModel()
            {
                ShoppingCartItems = _shoppingCartServices.ShoppingCartItems,
                ShoppingCartTotal = _shoppingCartServices.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }
        public async Task<IActionResult> AddToShoppingCart(int shirtId)
        {
            var selectedShirt = await _shirtRepository.GetShirtBy(shirtId);
            if(selectedShirt != null)
            {
                _shoppingCartServices.AddToCart(selectedShirt, 1);
            }
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> RemoveFromShoppingCart(int shirtId)
        {
            var selectedShirt = await _shirtRepository.GetShirtBy(shirtId);
            
            if(selectedShirt != null)
            {
                _shoppingCartServices.RemoveFromCart(selectedShirt);
            }
           return RedirectToAction("Index");
        }
        public async Task <IActionResult>Submit(ShoppingCartViewModel shoppingCartViewModel)
        {
            if(shoppingCartViewModel.ShoppingCartItems.Count > 0)
            {

            }
            return RedirectToAction("Checkout", "Order");
        }
    }
}

TShirtShop/Views/Shared/_AddAndCancelButton.cshtml
<div class="form-group">
    <div class="offset-md-3 col-md-3">
        <input type="submit" class="btn btn-success btn-lg custom-button" value="SAVE" />
        <a asp-action="Index" class="btn btn-danger btn-lg">CANCEL</a>
    </div>
</div>

TShirtShop/Views/Shared/_AdminNav.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Content Management
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" asp-action="Add" asp-controller="Shirt">Add T-Shirt</a></li>
        </ul>
    </li>
}

TShirtShop/Views/Shared/_ImageModal.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="myModal" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen-sm-down">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <img class="img-fluid" src="#" id="imageView" alt="" />
            </div>

        </div>

    </div>
</div>

TShirtShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/css/bootstrap.css" rel="stylesheet" />
    <script src="~/jquery/jquery.js"></script>

    <script src="~/lib/js/bootstrap.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs5/dt-1.11.2/datatables.min.css" />
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.2/datatables.min.js"></script>
    <script src="https://kit.fontawesome.com/53e9e8cd4d.js" crossorigin="anonymous"></script>
    <link href="~/content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">The Programmers' shirts</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Index" asp-controller="Shirt">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact Us</a>
                    </li>
                    <partial name="_AdminNav" />
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    @RenderSection("Scripts",required:false)
</body>
</html>

TShirtShop/Views/Shared/_ShirtCard.cshtml
@model Shirt
    <div class="col">
        <div class="card">
            <img class="card-img-top" src=@Model.ImageThumnNailLocation alt="Shirt" />
            <div class="card-body">
                <h3 class="">@Model.Price</h3>
                <h3>@Model.Name</h3>
                <p>@Model.Description </p>
            </div>
            <div class="addToCart">
                    
                        <a class="btn btn-primary"
                           asp-controller="ShoppingCart"
                           asp-action="AddToShoppingCart"
                           asp-route-shirtId="@Model.ShirtId"
                           >Add to Cart</a>
            </div>
        </div>

    </div>